//---
//共有JavaScript
//by Jason Yang 2015/2/7
//---
$("#systemBrand").click(function(){
    //链接至系统主页面
});
$("#usrName").click(function(){
    //链接至用户个人主页
});
$("#usrAvator").click(function(){
    //链接至用户信息修改页
});
$("#notifacations").click(function(){
    //链接至用户消息页面
});
$("#exit").click(function(){
    //退出登录
});